#!/bin/bash

# 1. Roda o script de Bioinformática
python3 filtro_blast.py

# 2. Pergunta se deseja enviar os resultados para o GitHub
echo ""
read -p "Deseja enviar as atualizações para o GitHub agora? (s/n): " resposta

if [ "$resposta" == "s" ]; then
    echo "🚀 Preparando o envio..."
    git add .
    git commit -m "Atualização automatizada: $(date +'%d/%m/%Y %H:%M')"
    git push origin main
    echo "✅ Tudo pronto no GitHub, Ricardo!"
else
    echo "🏠 Arquivos salvos apenas localmente."
fi
